database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
#    - "5434:5432"
    - "5435:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: transitiegas
    POSTGRES_DB: transitiegas

builder:
  build: .
  links:
    - database:database
  ports:
    - "8080:8080"
  environment:
    DATABASE_NAME: atlas
    DATABASE_PASSWORD: insecure
  volumes:
    - ./data:/data
    - ./convertors:/convertors
