version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: gastransitie
      POSTGRES_DB: gastransitie
    ports:
      - 5435:5432
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  importer:
    build: src
    links:
      - database
    environment:
      DATABASE_NAME: gastransitie
      DATABASE_USER: gastransitie
      DATABASE_PASSWORD: insecure
      GASTRANSITIE_OBJECTSTORE_PASSWORD:
      GASTRANSITIE_USE_LOCAL:
    volumes:
      - ./data:/data
    command: >
      bash -c "/app/docker-wait.sh \
               && /app/run_import.sh"

  web:
    build: web
    links:
      - database
    environment:
      DATABASE_NAME: gastransitie
      DATABASE_USER: gastransitie
      DATABASE_PASSWORD: insecure
      GASTRANSITIE_OBJECTSTORE_PASSWORD:
    ports:
      - "8000:8000"
    volumes:
      - ./web/data:/data
      - ./web/app:/app/
      - ./web/deploy:/deploy
    command: >
      bash -c "/deploy/docker-wait.sh \
              && /deploy/docker-migrate.sh \
              && python manage.py runserver 0.0.0.0:8000"
