version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: gastransitie
      POSTGRES_DB: gastransitie
    ports:
      - 5435:5432
    volumes:
      - tmpdatabase:/tmp

  importer:
    #image: build.datapunt.amsterdam.nl:5000/datapunt/gastransitie:${ENVIRONMENT}
    build: importer
    links:
      - database
    environment:
      DATABASE_NAME: gastransitie
      DATABASE_USER: gastransitie
      DATABASE_PASSWORD: insecure
      GASTRANSITIE_OBJECTSTORE_PASSWORD:
      PGPASSWORD: insecure
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-wait.sh \
               && /app/import.sh"

volumes:
   tmpdatabase:
