version: '3.0'
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: gastransitie
      POSTGRES_DB: gastransitie
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/gastransitie:${ENVIRONMENT}
    links:
      - database
    environment:
      DATABASE_NAME: gastransitie
      DATABASE_USER: gastransitie
      DATABASE_PASSWORD: insecure
      GASTRANSITIE_OBJECTSTORE_PASSWORD:
    volumes:
      - ./import_cache:/data
    command: >
      bash -c "/deploy/import.sh"
